import Head from 'next/head';
import { useState } from 'react';
import Login from './login';

export default function Home() {
	const [email, setEmail] = useState('');
	const [password, setPassword] = useState('');

	function inputHandler(e: React.ChangeEvent<HTMLInputElement>) {
		const type = e.target.name;
		switch (type) {
			case 'email':
				setEmail(e.target.value);
				break;
			case 'password':
				setPassword(e.target.value);
				break;
		}
	}

	return (
		<>
			<Head>
				<title>Sign in</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				{/* <link rel='icon' href='/favicon.ico' /> */}
			</Head>
			<header></header>
			<main>
				<Login inputHandler={inputHandler} email={email} password={password} />
			</main>
		</>
	);
}
